Calendar/config/routes.rb
CalendarExample::Application.routes.draw do
  resource :calendar, controller: :calendar
  root to: "calendar#index"
  get "calendar/show"
end

Calendar/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Calendar/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Calendar/app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def index
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @months = {1 => "January", 
              2 => "February",
              3 => "March",
              4 => "April", 
              5 => "May", 
              6 => "June", 
              7 => "July", 
              8 => "August", 
              9 => "September", 
              10 => "October", 
              11 => "November", 
              12 => "December"}
  end
  def show
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end
end

Calendar/app/helpers/application_helper.rb
module ApplicationHelper
end

Calendar/app/helpers/calendar_helper.rb
module CalendarHelper
    def calendar(date = Date.today, &block)
        Calendar.new(self, date, block).table
    end
end

Calendar/app/views/calendar/index.html.erb
<h1>Welcome in calendar app</h1>
<h3>Year: <%= @date.year%></h3>
<p>Click month:</p>
<div class="container">
<div class="row">

<% @months.each do |num, month| %>
    <div class="col-sm-1">
<%= link_to calendar_path(date: @date.change(month: num)) do %>
    <%= month %>
<% end %>
</div>
<% end %>


</div>
</div>

Calendar/app/views/calendar/show.html.erb
<h1>Welcome in calendar app</h1>
<div class="row">
  <div class="col-md-12 text-center">
    <div class="well controls">
      <%= link_to calendar_path(date: @date - 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-backward"></i>
      <% end %>
      <%= "#{@date.strftime("%B")} #{@date.year}" %>
      <%= link_to calendar_path(date: @date + 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-forward"></i>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= calendar @date do |date| %>
      <%= date.day %>
    <% end %>
  </div>
</div>

Calendar/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CalendarExample</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "http://yandex.st/bootstrap/3.0.2/css/bootstrap.min.css", media: "all" %>
  <%= javascript_include_tag "http://yandex.st/bootstrap/3.0.2/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= yield %>
</div>

</body>
</html>